- requirements_afaas.txt
> Added all the requirements in the requirements_afas.txt

- autogpts/autogpt/Dockerfile
- Removed firefox-esr package to reduce image size
- Added --no-cache flag to poetry install steps
- Removed source code files after installation to reduce image size
> build: Reduce AutoGPT Docker image size

- AFAAS/interfaces/agent/main.py
Fixes #39
Remove commented code and unused method in BaseAgent
Clean up BaseAgent by removing commented code and an unused method. This
improves code readability and maintainability. Fixes #39
> Remove commented code in BaseAgent

- .vscode/settings.json
> Add tests settings to .vscode

- .github/workflows/afaas-label-contributor.yml
> 🏗️: Add contributor label to issues & PR made by contributors

- AFAAS/interfaces/prompts/strategy.py
> Remove commented code in strategy.py

- app/cli_app/main.py
> Constantly use LOG.level <= LOG.DEBUG in cli_app/main.py

- .github/workflows/afaas-changelog.yml
> Add console.log debug message for easier debugging

- AFAAS/interfaces/agent/main.py
> Remove unused variables

- AFAAS/core/agents/planner/main.py
- AFAAS/core/agents/usercontext/main.py
- AFAAS/interfaces/agent/abstract.py
- AFAAS/interfaces/workflow.py
- AFAAS/prompts/common/afaas_task_post_rag_update.jinja
- AFAAS/prompts/common/afaas_task_post_rag_update.py
Set foundation for different workflows. 
Add workflow concept, currently not used but it might be either used or merged with the Pipeline.
> Add workflow concept. This concept might letter be merged with the Pipeline.

- AFAAS/interfaces/agent/main.py
> Fix save_agent_in_memory()

- .github/ISSUE_TEMPLATE/1.bug.yml
- .github/ISSUE_TEMPLATE/2.feature.yml
> 🏗️ : Improve Issue Templates

- AFAAS/core/agents/planner/loop.py
- AFAAS/interfaces/agent/features/agentmixin.py
- AFAAS/lib/task/task.py
- AFAAS/prompts/common/afaas_task_post_rag_update.jinja
- AFAAS/prompts/common/afaas_task_post_rag_update.py
- app/cli_app/main.py
> 🐞 : Various fix comming from monkey testing v0.0.0-dev

- AFAAS/prompts/common/afaas_task_post_rag_update.jinja
> 🐞 : Fix task history skipped in the task RAG process

- AFAAS/core/tools/builtins/query_language_model.py
- AFAAS/interfaces/agent/assistants/prompt_manager.py
- AFAAS/prompts/common/__init__.py
- AFAAS/prompts/common/query_llm.jinja
- AFAAS/prompts/common/query_llm.py
- tests/conftest.py
- tests/test_tools_query_large_language_model.py
> ✨ : Set a tool that cleverly query language model

- AFAAS/core/tools/simple.py
- AFAAS/core/tools/tools.py
> 🔧 : Add a method to transform a Tool into an OpenAI Function Tool

- AFAAS/interfaces/task/task.py
> Add missing RAG-related attriibutes in Task Interface

- app/cli_app/main.py
> 🐞 : Agent Creation Error Resolved for Non-Digit Input

- AFAAS/core/adapters/embeddings/__init__.py
- AFAAS/core/adapters/embeddings/search.py
- AFAAS/core/tools/builtins/user_interaction.py
- AFAAS/core/tools/tool.py
- AFAAS/interfaces/agent/abstract.py
- AFAAS/interfaces/agent/assistants/prompt_manager.py
- AFAAS/interfaces/prompts/strategy.py
- AFAAS/interfaces/task/base.py
- AFAAS/lib/message_agent_user.py
- AFAAS/lib/sdk/logger.py
- AFAAS/lib/task/task.py
- AFAAS/prompts/common/__init__.py
- AFAAS/prompts/common/afaas_smart_rag.jinja
- AFAAS/prompts/common/user_proxy.jinja
- AFAAS/prompts/common/user_proxy.py
- poetry.lock
- pyproject.toml
- tests/test_tools_user_interaction.py
> ## Title: User Interaction Tool with Proxy Support for Agent-Based Framework
> ### Description:
> The tool, named "user_interaction," is designed to facilitate communication between an agent and a user in a system that relies on an embedding model and a vector store to manage and respond to user queries. The primary function of this tool is to ask users for additional details or information regarding their goals or queries.
> 
> ### Key Features:
> #### Query Handling:
> The tool accepts a user query as input and creates a message from the agent to the user. It can also handle responses from the user.
> 
> #### Proxy Integration:
> Before directly interacting with the user, the tool checks if a proxy can provide an answer based on past interactions stored in a vector store. The proxy …
> ✨ : User proxy : Provide answer to trivial questions that do not requires a user intervention

- AFAAS/interfaces/agent/assistants/prompt_manager.py
- AFAAS/interfaces/agent/features/agentmixin.py
This pull request introduce the capability to dynamically load prompts used by agents. This feature streamlines the process of incorporating new prompts. This development is a foundational step, setting the stage for future advancements like loading prompts from plugins and overriding existing framework prompts with plugin-sourced alternatives.
- Simplified Prompt Integration:
The update allows for the effortless addition of new prompts into the system, significantly enhancing the framework's versatility and user-friendliness.
- Foundation for Plugin-Based Prompts:
This PR lays the groundwork for subsequent updates, where the system will evolve to support prompt loading for each plug-in to extend or overwrite the framework.
The PR includes changes in key files such as prompt_manager.py …
> 🔧 : Prompts : Prompts used by the agents loads dynamically

- AFAAS/core/agents/planner/main.py
- AFAAS/core/agents/usercontext/main.py
- AFAAS/core/tools/builtins/file_operations_helpers.py
- AFAAS/interfaces/agent/abstract.py
- tests/conftest.py
- tests/test_tools_file_operations_helpers.py
Draft PR, presentation of the PR will be detailed soon.
> 🔧 : A user can configure the folder where logs are stored

- AFAAS/plugins/tools/__to_be_migrated/web_selenium.py
Add the commit 31c85c6a14e365066bf6382272b823110efe67a3  / PR #6778
And ignore other commits.
> 🔄 Fix agpt merge

- AFAAS/core/agents/planner/loop.py
- AFAAS/lib/task/plan.py
- AFAAS/lib/task/task.py
> 🐞 : Patch : Fix Main Agent Loop

- AFAAS/lib/task/plan.py
> 🐞 : Fix a bug that mixed the order of tasks that are ready

- AFAAS/core/agents/planner/main.py
- AFAAS/core/agents/prompt_manager.py
- AFAAS/core/agents/usercontext/main.py
- AFAAS/core/tools/builtins/afaas_make_initial_plan.py
- AFAAS/core/tools/builtins/afaas_refine_user_context.py
- AFAAS/core/tools/builtins/afaas_routing.py
- AFAAS/core/tools/builtins/execute_code.py
- AFAAS/core/tools/builtins/file_operations.py
- AFAAS/core/tools/builtins/not_implemented_tool.py
- AFAAS/core/tools/builtins/query_language_model.py
- AFAAS/core/tools/builtins/search_info.py
- AFAAS/core/tools/builtins/user_interaction.py
- AFAAS/core/tools/tool.py
- AFAAS/core/tools/tool_registry.py
- AFAAS/interfaces/agent/abstract.py
- AFAAS/interfaces/agent/assistants/prompt_manager.py
- AFAAS/interfaces/agent/features/agentmixin.py
- AFAAS/interfaces/tools/base.py
- AFAAS/interfaces/tools/tool.py
- AFAAS/prompts/common/afaas_task_postprocess_default_summary.py
- AFAAS/prompts/common/query_llm.py
- AFAAS/prompts/common/search_info.py
- AFAAS/prompts/common/user_proxy.py
This pull request introduces two new foundational classes, AbstractPromptManager and AFAASBaseTool, aimed at establishing clear interfaces for managing prompts and tools within the AFAAS ecosystem. These interfaces are designed to provide a structured framework that facilitates the development, maintenance, and extension of the system's components.
AbstractPromptManager Interface: The AbstractPromptManager class is introduced as an interface to outline the expected functionalities of a PromptManager. This interface includes method signatures that are crucial for managing the lifecycle of prompts, including but not limited to, loading, selecting, and executing prompt strategies. This abstraction ensures that any implementation of a PromptManager adheres to a defined contract, enhancing …
> 🔧 : Introducing interfaces `AbstractPromptManager`and `AFAASBaseTool`

- AFAAS/core/agents/planner/loop.py
> 🔧 : `PlannerAgent` loop cleansing

- .coveragerc
- AFAAS/core/agents/planner/main.py
- AFAAS/core/db/table/nosql/message_user_agent.py
- AFAAS/core/tools/builtins/user_interaction.py
- AFAAS/lib/message_user_agent.py
- AFAAS/prompts/common/autocorrection.py
- AFAAS/prompts/routing/select_planning.py
- AFAAS/prompts/usercontext/refine_user_context.py
- tests/test_message_agent_user.py
omit =
AFAAS/core/user/*
AFAAS/core/ability/*
AFAAS/lib/message_agent_*
AFAAS/core/db/nosql/cosmodb.py
AFAAS/core/db/nosql/dynamodb.py
AFAAS/core/db/nosql/mongodb.py
AFAAS/core/db/sqllikejsonfile.py
AFAAS/core/db/table/nosql/message_agent_*
> 🏗️ : Remove unused files from code coverage

- AFAAS/core/adapters/openai/chatmodel.py
- AFAAS/core/adapters/openai/configuration.py
- AFAAS/core/agents/prompt_manager.py
- AFAAS/interfaces/adapters/__init__.py
- AFAAS/interfaces/adapters/chatmodel/chatmodel.py
- AFAAS/interfaces/adapters/chatmodel/wrapper.py
- AFAAS/interfaces/adapters/language_model.py
- AFAAS/interfaces/agent/main.py
- AFAAS/interfaces/prompts/strategy.py
> 🔧 : Remove has_oa_function_call()
